### ISSUE TITLE
'Analytics/SEGAnalytics.h' file not found

### ISSUE THREAD

**Issue by wangjoshuah** [segmentio/analytics-react-native#17]
When following the React Native install instructions, I get a error
```
'Analytics/SEGAnalytics.h' file not found
```

**Comment by caroaguilar** [comment]
This is happening to me too. I'm not using Cocoapods, I followed the steps to add segment manually.
![screen shot 2018-11-06 at 11 37 40 am](https://user-images.githubusercontent.com/1471138/48082707-e363ca00-e1b8-11e8-946d-9029919a56fa.png)

**Comment by caroaguilar** [comment]
After adding the beta I got the project to build on Xcode however I'm still seeing an error in the simulator "Failed to load Analytics native module" when building the react native app

**Comment by gre** [comment]
@fathyb the problem is the Framework Search Paths. this fixes the problem:

- add `Analytics.framework` to `RNAnalytics`’s `Building Settings` :  into `Framework Search Paths` your put `$(SRCROOT)/../../../../ios`
- then in `RNAnalytics`’s `Build Phases` you add a `Copy Files` phase where you put `Analytics.framework` (basically you can drag and drop the one under `RNAnalytics/Frameworks` on Xcode)

**Comment by ravirupareliya** [comment]
Did any one get solution? I have tried with both the way, but none of is working for me

**Comment by caroaguilar** [comment]
Thank you @gre! I can confirm that fixes the problem for me.

**Comment by fathyb** [comment]
Thanks for all the information @gre and @caroaguilar! We'll look into it shortly and test Xcode 10 releases. It looks like you're experiencing a different issue than OP though (`'Analytics/SEGAnalytics.h' file not found`). #19 is the right issue, let's continue there.

**Comment by caroaguilar** [comment]
@fathyb actually the issue I was having was `Analytics/SEGAnalytics.h' file not found` which is this one and I was able to get it to work with @gre solution. And thanks for looking into it.

**Comment by ttuck303** [comment]
@gre's second solution worked, thanks

**Comment by fathyb** [comment]
Sorry for the confusion @caroaguilar!
We've improved support for users using iOS manually and added E2E tests in `0.0.1-beta.3`, could you try it out? It's based on [@gre's comment](https://github.com/segmentio/analytics-react-native/issues/17#issuecomment-444216917) (thanks for that!). Be sure to follow the [migrations instructions](https://github.com/segmentio/analytics-react-native/blob/master/CHANGELOG.md#migration-instructions).

Please let us know if you're still experiencing any issues.

**Comment by jnystrom** [comment]
I am getting error when adding the GitrHub ref to the package: `npm ERR! premature close`?

**Comment by CapitanRedBeard** [comment]
For anyone wondering the fix above also works for Carthage (which is lot closer to a manual install than the automatic install CocoaPods offers) 

@gre 's Second comment fixed the issue for me minus the first part about including the package in my package.json, since Carthage already fetches the Analytics project. I just had to drag the `Analytics.xcodeproj` from my `Carthage/Checkouts/analytics-ios/` directory into XCode Libraries at the same level as `RNAnalytics.xcodeproj`

Cheers!

**Comment by gluix20** [comment]
> I am getting error when adding the GitHub ref to the package: `npm ERR! premature close`? I am also not upgrading, this if just from installing the beta3 fresh.
> 
> I have tried to use the CocoaPods way as well, and it does not build either.

As segmentio/analytics-ios repo doesn't have package.json, you have to clone it with Carthage as @CapitanRedBeard said.

**Comment by AmitPandya007** [comment]
> This is happening to me too. I'm not using Cocoapods, I followed the steps to add segment manually.
> ![screen shot 2018-11-06 at 11 37 40 am](https://user-images.githubusercontent.com/1471138/48082707-e363ca00-e1b8-11e8-946d-9029919a56fa.png)

@caroaguilar  will you please help me out. I have tried all the solutions but still I am getting the same error. I am chasing this error from 2 to 3 days. Please help me out.

**Comment by caroaguilar** [comment]
@AmitPandya007 All I did at that time was @gre's solution and it worked. At the end after having this same problem with a couple of different libraries we ended up integrating Cocoapods to the app and since [React Native now uses Cocoapods](https://facebook.github.io/react-native/blog/2019/07/03/version-60#cocoapods-by-default) by default starting on version 0.60 I think the best way to go is to update to RN 0.60 (if needed) and use Cocoapods

**Comment by AmitPandya007** [comment]
will it work if I upgrade my React-Native version?

**Comment by caroaguilar** [comment]
@AmitPandya007 well you should try, it's working for me using Cocoapods. You can use the [React Native upgrade helper](https://react-native-community.github.io/upgrade-helper/) and follow the steps for Segment docs https://github.com/segmentio/analytics-react-native#installation

**Comment by AmitPandya007** [comment]
> @AmitPandya007 well you should try, it's working for me using Cocoapods. You can use the [React Native upgrade helper](https://react-native-community.github.io/upgrade-helper/) and follow the steps for Segment docs https://github.com/segmentio/analytics-react-native#installation

Thanks a lot for your time and reply.
