### ISSUE TITLE
Setup Integrations before setting up Core

### ISSUE THREAD

**Issue by barodeur** [segmentio/analytics-react-native#172]
Hello,

We noticed that some events are sent to `Mixpanel` in Server Mode instead of Device Mode.
Events that happens early in the initialization like the Segment's life-cycle event "Application Installed" are sent in Server Mode.

Looking at the source code for `1.1.0`, it appears that there is a clear intent to wait for each integration to be setup before the core is initialized:

https://github.com/segmentio/analytics-react-native/blob/3df275f3419ee7536a811b914b901dab6ee2b46f/packages/core/src/configuration.ts#L35-L39

However the `setup` call for each integration is not returning a `Promise<void>` but just `void`: https://github.com/segmentio/analytics-react-native/blob/3df275f3419ee7536a811b914b901dab6ee2b46f/packages/integrations/template/ios/main.m#L20-L22

Given that the React Native bridge itself is asynchronous, I don't see guarantee that the integrations are setup before life-cycle events are sent.

Could this be the cause of those event being sent in Server Mode instead of Device Mode?

**Comment by bsneed** [comment]
It definitely could be.  We've been investigating this internally from another issue report over the last few days.  Will report back with what we find.

**Comment by bsneed** [comment]
tagging @prayansh

**Comment by bsneed** [comment]
Due to the nature of React Native, app lifecycle events are sent before RN is actually up and running which is why you're potentially seeing it in cloud mode.  We did a fix, which might be at play here as well, a little while back where the settings received from segment.com were not being cached properly.  It affected all events though, not just lifecycle, just an FYI in case you're seeing that as well.
