### ISSUE TITLE
Lack of events in middleware

### ISSUE THREAD

**Issue by kasterlod** [segmentio/analytics-react-native#183]
Hello!

I can see only **custom events (sent by me)** using middleware. Any possibilities to get lifecycle & attribution related events here? I'll appreciate any ideas 🙏 

```
analytics.setup(<key>, {
      using: [AppsFlyer],
      trackAttributionData: true,
      trackAppLifecycleEvents: true
    })
  analytics.middleware(({ next, context, data }) => {
    console.log(data)

    return next(context)
  })
```

"@segment/analytics-react-native": "1.1.0"
"react-native": "0.62.2"

**Comment by bsneed** [comment]
@kasterlod You should get any lifecycle events that are fired after your middleware is set.  However, the way react-native works, most of the events you'd see on startup have already been fired on the native side by the time setup has exited and before your call to set the middleware.  The underlying issue is that via RN, the setup happens too late.  We're planning on addressing that in the future, but it's more of a general issue and not related to middleware really.  If you file an issue with our support team, it'll help move this up in priority.

**Comment by AlexeyNovikov** [comment]
> @kasterlod You should get any lifecycle events that are fired after your middleware is set. However, the way react-native works, most of the events you'd see on startup have already been fired on the native side by the time setup has exited and before your call to set the middleware. The underlying issue is that via RN, the setup happens too late. We're planning on addressing that in the future, but it's more of a general issue and not related to middleware really. If you file an issue with our support team, it'll help move this up in priority.

I don't see any lifecycle events, even after the app is loaded. For example "https://segment.com/docs/connections/spec/mobile/#application-opened". I'm testing on iOS.
