### ISSUE TITLE
Android crash on new version 4.9.0 - Could not create instance of com.segment.analytics.Properties.

### ISSUE THREAD

**Issue by Eden-Eliel** [segmentio/analytics-react-native#227]
Hello segement team,
A day or 2 ago, we tried to release a version for our app, but the android app crashed whenever it was opened.

the logcat of the eror:

```
10-18 17:40:26.718 10140 10140 E AndroidRuntime: java.lang.AssertionError: Could not create instance of com.segment.analytics.Properties.
10-18 17:40:26.718 10140 10140 E AndroidRuntime: java.lang.NoSuchMethodException: com.segment.analytics.Properties.<init> [interface java.util.Map]
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.ValueMap.createValueMap(SourceFile:70)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.ValueMap.coerceToValueMap(SourceFile:343)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.ValueMap.getValueMap(SourceFile:329)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.integrations.TrackPayload.properties(SourceFile:84)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.android.integrations.mixpanel.MixpanelIntegration.track(SourceFile:283)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.IntegrationOperation.track(SourceFile:291)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.IntegrationOperation$8$1.invoke(SourceFile:216)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.MiddlewareChainRunner.proceed(SourceFile:64)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.IntegrationOperation.runMiddlewareChain(SourceFile:184)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.IntegrationOperation$8.run(SourceFile:199)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.Analytics.performRun(SourceFile:1596)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.segment.analytics.Analytics$10.run(SourceFile:774)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7710)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
10-18 17:40:26.718 10140 10140 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

After a little bit of investigation, I saw that the android version was uploaded to 4.9.0, and I think that's what made the issue to occurred. 

a quick fix for it was to force the package to downgrade : 
```
node_modules/@segment/analystics-react-native/android/build.gradle
```

```
dependencies {
    api 'com.segment.analytics.android:analytics:4.8.2'

    api 'com.facebook.react:react-native:+'
    api "org.jetbrains.kotlin:kotlin-stdlib:${rootProject.ext.has("kotlinVersion") ? rootProject.ext.get("kotlinVersion") : defaultKotlinVersion}"
}
```

RN version: "0.63.3"
analystics-react-native version: 1.3.1

Thanks ahead, Eden

**Comment by martintreurnicht** [comment]
We had the same issue, our app actually made it all the way to the playstore (it was built by the CI system) and we had to scramble to fix the issue, and we're still dealing with the fallout from it. Segment should NOT be using dynamic versions in their dependencies. It's something that is actually very strongly discouraged by Gradle because of how unpredictable it is

**Comment by kartikk** [comment]
We ran into the same issue. Reverting `analystics-react-native` to `1.3.0` fixes the crash for us.
I agree with @martintreurnicht on not using dynamic versioning for dependencies, for the sake of repeatable builds.

**Comment by prayansh** [comment]
Hi! It is surprising that this issue is surfacing now, even though we havent changed any internals related to the same. This exception is being thrown because proguard is minifying/obfuscating some of our analytics classes.

The easiest way to fix this and stay on the latest version would be to include this rule in your proguard configuration (this usually lives under `android/app/proguard-rules.pro`)
```
-keepclassmembers class com.segment.analytics.** extends com.segment.analytics.ValueMap {
  <init>(java.util.Map);
}sss
```

**Comment by martintreurnicht** [comment]
@prayansh I would not close this issue, this is still a very real problem. Using dynamic version numbers in Gradle is a REALLY bad idea, i don't really understand the need for it either, if you need to pull in a specific version you could just release a new version of this library. If you don't do that then untested released of https://github.com/segmentio/analytics-android can get pulled in by this library at anytime.

The reason why this is such a big issue is because Gradle does not have a good way to lock dependencies like NodeJS or Ruby, so when you use dynamic versions like this it's really hard to predict what the issue is. And even verifying this fix that you propose is hard, because I need to purge my local build cache and force it to pull in 4.9.0 instead.

I think the right thing to do here is just pin the version, the reason why all the other versions never had this problem is because the https://github.com/segmentio/analytics-android version used to be pinned before `1.3.1`.

i mean it's a analytics library i don't think anyone is worried that they're not going to get the latest greatest features, stability is more important than features in this case.

As a side note, Gradle does actually have a version locking system, but it's pretty bad. Even so, we've added it to our project for an extra level of protection, just as a way to ensure that builds are consistent. But it's not the norm, and you can't really depend on people using it.

The proguard change did in fact fix the issue

**Comment by martintreurnicht** [comment]
It seems that version has been made static again in this commit https://github.com/segmentio/analytics-react-native/commit/9b5734d58b3f4099b5396504debb4ffad2abdd79

I'd advice anyone on version `1.3.1` to upgrade to `1.3.2` or downgrade to `1.3.0`

**Comment by amitassaraf** [comment]
Note this is still broken on Android on version `1.3.2` regardless of the #230 PR. What worked for me is downgrading manually the library inside `react-native-analytics` to `4.8.2` from `4.9.0`

**Comment by amitassaraf** [comment]
Please reopen this issue @prayansh
