### ISSUE TITLE
iOS crashing (duplicate symbol)

### ISSUE THREAD

**Issue by lyshchenkosergiy** [segmentio/analytics-react-native#242]
Hi there,

We are using version 1.3.1 of this package together with https://github.com/PostHog/posthog-react-native (version 1.0.1).
We noticed, that when we are building our app for iOS (doesn't matter simulator or a real device), we are facing such issue.

Issue screenshot:
![1111](https://user-images.githubusercontent.com/37838803/100445609-0e7a2880-30b6-11eb-8fe5-453f2320044e.jpeg)

Environment:
React Native: 0.63.2; XCode version: 12; Simulator/device: iPhone Xr, iOS 14;

At the same time Android build works well.
Does anyone here know what might be wrong and how this issue can be fixed?

**Comment by alanjcharles** [comment]
Hi,

Thanks for sending this over! I'm taking a look and will let you know as soon as I can.

**Comment by alanjcharles** [comment]
@lyshchenkosergiy it seems Posthog is a direct copy of Segment: 

https://github.com/PostHog/posthog-ios/blob/master/LICENSE

Since you can't have two static libs with the same functionality in them, you will have to build with a framework. We recommend Cocoapods. Alternatively, it might be worth reaching out to the Posthog team to see if they have a way to use both packages simultaneously. Please let me know if there is anything else we can help you with!
