### ISSUE TITLE
iOS build fails with react-native-appboy-sdk@1.2.7 and analytics-react-native-appboy@1.4.3

### ISSUE THREAD

**Issue by jwebcat** [segmentio/analytics-react-native#284]
We use both the `react-native-appboy-sdk` alongside the `analytics-react-native-appboy` integration. After upgrading `react-native-appboy-sdk` to `v1.2.7` which relies on `pod 'Appboy-iOS-SDK', '3.33.1'` the build fails with the following error in Xcode:

<img width="1164" alt="Screen Shot 2021-03-17 at 11 55 14 AM" src="https://user-images.githubusercontent.com/2264388/111522542-a3fa0080-8717-11eb-9114-ebd8308e2965.png">

I tried upgrading to `analytics-react-native-appboy@1.4.3` but the same issue persists.

With `analytics-react-native-appboy@1.4.1` and `react-native-appboy-sdk@1.2.6` everything works as expected.

**Comment by BerniWittmann** [comment]
Same issue here while not using `react-native-appboy`

**Comment by alanjcharles** [comment]
@jwebcat Can I ask why you are using both SDKs side by side? When you use `analytics-react-native-appboy` the `analytics-react-native` sdk will pull the appboy SDK into your app. 

I'm going to close this since we don't support adding both SDKs to one implementation so this is not something we will be able to provide a fix for. Please let me know if there is anything else you would like me to consider before closing this out.

**Comment by jwebcat** [comment]
@alanjcharles sure, we need to leverage the JS API that the `react-native-appboy-sdk` RN provides for inbox and cards etc. 

Before closing, the same is occurring for @BerniWittmann even without using `react-native-appboy-sdk` any insight there?

**Comment by jwebcat** [comment]
@alanjcharles Thank you, much appreciated. We are on the latest `analytics-react-native@1.4.1`

**Comment by BerniWittmann** [comment]
@alanjcharles `@segment/analytics-react-native: 1.4.1` as well , Thank you

**Comment by j-fro** [comment]
@BerniWittmann @jwebcat if you're still having this issue, I just resolved it on my end: https://github.com/segmentio/analytics-react-native/issues/305#issuecomment-827141282

**Comment by alanjcharles** [comment]
@BerniWittmann @jwebcat Please reopen if @j-fro 's solution doesn't help. Copied here for context: 

`This is resolved. It appears that since the iOS SDK is no longer pinned to a version in the Podspec, it was using the previous (incompatible) version from my Podfile.lock. Removing that line (- Analytics (3.9.0) and running pod install again fixed it.`

If the issue does persist, please let me know which version of `analytics-ios` is included in your `podfile.lock`. Thanks!
