### ISSUE TITLE
@segment/analytics-react-native-branch throws No visible @interface for 'NSArray<BranchUniversalObject *>' declares the selector 'addObject:'

### ISSUE THREAD

**Issue by wmcbain** [segmentio/analytics-react-native#294]
Hi there,

We're trying to pass the segment anonymous id to branch using the method described here: https://help.branch.io/using-branch/docs/segment-export#pass-segment-anonymous-id. However since we're initializing Segment from the react-native side of things it's a little unclear how to pass the anonymous idea to branch. We thought that https://www.npmjs.com/package/@segment/analytics-react-native-branch might wrap this for us.

When we go to build using the @segment/analytics-react-native-branch package we get the following error:

```
No visible @interface for 'NSArray<BranchUniversalObject *>' declares the selector 'addObject:'
```

<img width="450" alt="Screen Shot 2021-04-02 at 12 37 06 PM" src="https://user-images.githubusercontent.com/7080654/113440263-16c2d700-93ba-11eb-95b5-02df4dd26c03.png">

Environment:
- react-native: 0.63.4
- @segment/analytics-react-native: 1.4.3
- @segment/analytics-react-native-branch: 1.4.3
- react-native-branch: 5.0.1

If using @segment/analytics-react-native-branch is not the proper way to give branch events the segment anonymous id is there another way we're supposed to initialize the package?

Appreciate any help.

**Comment by alanjcharles** [comment]
Hi @wmcbain ! 

So, the `@segment/analytics-react-native-branch` package is essentially "just" a wrapper for the underlying native Segment <> Branch integrations. Those are both owned and maintained by the Branch team and this is something they would have to fix, I'm afraid. [According to our documentation](https://segment.com/docs/connections/destinations/catalog/branch-metrics/), all of the Branch <> Segment SDKs are in maintenance mode. With that in mind, I would reach out to them for any additional troubleshooting or information regarding updates to their implementations. Please feel free to reopen if they provide any information you think we can use. Thanks!  

Additional Reference: 

[IOS Repo](https://github.com/BranchMetrics/Segment-Branch-iOS)
[Android Repo](https://github.com/BranchMetrics/Segment-Branch-Android)

**Comment by AnasMK9** [comment]
Hello there, I'm currently facing a similar situation and trying to follow the docs but to no hope. I found [this page](https://help.branch.io/faq/docs/how-do-i-pass-segment-anonymous-id-in-react-native-when-configuring-segment-export) in branch's docs which requires passing the anonymous ID on the native side of things, with no interfaces exported from the segment analytics to get the anonymous ID for a user, and a deprecation warning for v1.5.1 or older, which contain this functionality. 
To get around this issue I'm currently trying to pass the anonymous ID on the react native thread, but I'm not expecting much from this setup. One idea however, is to implement segment on the iOS side as well, and use the anonymous ID from there, but I'm not sure if this will work as expected or if the generated anonymous IDs will be the same.
It's been over a year since this issue was opened. Any thoughts on how this can be implemented?
