### ISSUE TITLE
`.h` files missing in react-native only on M1 Mac

### ISSUE THREAD

**Issue by Krisztiaan** [segmentio/analytics-react-native#310]
When running `pod install` on M1 Mac Mini, several `.h` files are missing, as well as the `LICENSE`, making the build fail.

Just adding `pod "Analytics", "4.1.3"` to the Podfile, it can be observed that there are serious differences in the `pod install` results.

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/4700811/116887809-0311c700-ac2b-11eb-91aa-91a69d5873dd.png">

Using `cocoapods` and `ruby` from `brew`.

The left side is adding the pod to a native iOS project, the right side is in a `react-native` context.

It works properly when the source is cloned, and pod is added via relative path.

**Comment by alanjcharles** [comment]
Hi @Krisztiaan, this seems to be a limitation of the M1 Mac rather than the `analytics-react-native` library itself. Looking around online, it seems a common issue for IOS builds on M1 Mac are related to not having Xcode installed correctly and/or having the correct path in your terminal. With that in mind, closing this out as there's not much we can do to account for this given current information. Please feel free to reopen with more information if this persists exclusively with the `analytics-react-native` library. Thanks and good luck!

**Comment by Krisztiaan** [comment]
@alanjcharles this is the only library out of several other dependencies that we have this issue with.

**Comment by 77TecShaeer** [comment]
+2

**Comment by Krisztiaan** [comment]
Using the `1.4.3` version instead of `1.4.4` solves this issue.
