### ISSUE TITLE
AppsFlyer SDK is obsolete

### ISSUE THREAD

**Issue by german970814** [segmentio/analytics-react-native#321]
I'm trying to upload my app to the play store and I'm getting this issue from google play console

![image](https://user-images.githubusercontent.com/15973868/118722061-48202680-b7f1-11eb-9ade-c775f9aa3abd.png)

This is my implementation

    "@segment/analytics-react-native": "1.4.5",
    "@segment/analytics-react-native-appsflyer": "1.4.5",
    "@segment/analytics-react-native-firebase": "1.4.5",
    "@segment/analytics-react-native-mixpanel": "1.4.5",

**Comment by alanjcharles** [comment]
@german970814 apologies, there's not much we can do to correct this, I'm afraid. All the `@segment/analytics-react-native-appsflyer` package does is pull in Appsflyer's underlying native SDKs. Since those are owned by Appsflyer, we don't have the ability to make fixes. 

The Android-specific `@segment/analytics-react-native-appsflyer`  [package is generated here and is pinned to >6.0](https://github.com/segmentio/analytics-react-native/blob/master/packages/integrations/integrations.yml#L107 ). I would recommend removing any reference in your dependency manager to outdated versions of Appsflyer. If the issue persists, I would recommend reaching out to friends@segment.com. They will be able to help you effectively troubleshoot and file a bug, if necessary :)

**Comment by german970814** [comment]
@alanjcharles actually I've removed all the references to appsflyer but the issue persists, I think segment package is pulling appsflyer sdk even if not is used anymore
