### ISSUE TITLE
analytics-react-native-appboy not compatible with latest version of react-native-appboy-sdk

### ISSUE THREAD

**Issue by vasuagrawal84** [segmentio/analytics-react-native#332]
Getting this error while installing pods. Looks like `analytics-react-native-appboy` needs an update to use the latest `Appboy-iOS-SDK`

```
[!] CocoaPods could not find compatible versions for pod "Appboy-iOS-SDK":
  In snapshot (Podfile.lock):
    Appboy-iOS-SDK (= 4.2.0, ~> 4.2.0)

  In Podfile:
    Appboy-iOS-SDK

    RNAnalyticsIntegration-Appboy (from `../node_modules/@segment/analytics-react-native-appboy`) was resolved to 1.4.8, which depends on
      Segment-Appboy was resolved to 4.1.0, which depends on
        Segment-Appboy/Full-SDK (= 4.1.0) was resolved to 4.1.0, which depends on
          Appboy-iOS-SDK (~> 4.1.0)

    react-native-appboy-sdk (from `../node_modules/react-native-appboy-sdk`) was resolved to 1.29.0, which depends on
      Appboy-iOS-SDK (~> 4.2.0)
```

`"react-native": "0.64.1"`
`"@segment/analytics-react-native": "1.4.8"`
`"react-native-appboy-sdk": "^1.29.0"`

**Comment by alanjcharles** [comment]
@vasuagrawal84 The Braze (appboy) integration isn't pinned so everything we push a new release it will pull in the latest native versions. I am able to build on `react-native 0.64.1` with the following packages: 

package.json
![image](https://user-images.githubusercontent.com/50601149/120857022-e88a8080-c53d-11eb-9c9a-c0d4b2b79e35.png)

podfile.lock
![image](https://user-images.githubusercontent.com/50601149/120857190-1a034c00-c53e-11eb-9db0-438c4081424d.png)

You might have to do a pod repo update or delete your pods and podfile.lock and install them again. Closing since I am unable to replicate. Please feel free to follow up with friends@segment.com for more troubleshooting advice. They can also help file and prioritize a bug report,  if necessary. Thanks!
