### ISSUE TITLE
Application Opened event is not tracked correctly on Android

### ISSUE THREAD

**Issue by masontranty** [segmentio/analytics-react-native#337]
### Environment:

RN: 0.64
Segment: 1.4.4
Platform: Android

I have a setup function here
`  async bootstrap(key: string): Promise<boolean> {
    await this.client?.setup(key, { trackAppLifecycleEvents: true });
    this.isReady = this.client?.ready ?? true;
    return this.isReady;
  }`
  and i call it on the app.tsx file

### Step to produce:
1. Kill app
2. Open app and look on the Debugger tab on Segment dashboard to catch the application opened event
3. Turn app into background state
4. Open app again

### Expectation: Events stack should be: 
1. Application Opened (from background = false) (should be tracked on step 2)
2. Application backgrounded
3. Application Opened (from background = true)

### Actual reuslt: 
1. Application Opened (from background = false) **( is tracked on step 3, that's weird)**
2. Application backgrounded
3. Application Opened (from background = true) (missing)

**Comment by alanjcharles** [comment]
Hi @masontranty can you try upgrading to `analytics-react-native 1.4.9`? We have added some new logic for lifecycle functionality on Android builds since `1.4.4`. If the problem persists, please reach out to friends@segment.com. They will be able to offer additional guidance and file a Jira, if necessary. Thanks!
