### ISSUE TITLE
`device.id` is `null` on Android

### ISSUE THREAD

**Issue by Kerumen** [segmentio/analytics-react-native#397]
On Android, we have `null` for the `device.id` key.

```
"device": {
  "id": null,
  "manufacturer": "Google",
  "model": "Pixel 3",
  "name": "blueline",
  "type": "android"
},
```

I've tracked it down to the `collectDeviceId` key which is read in the Java implement of `getContextInfo` but not passed in the call on the JavaScript side:

https://github.com/segmentio/analytics-react-native/blob/829fc80bc8c4f59fa99dadd25083efa422d577f0/packages/core/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt#L101

https://github.com/segmentio/analytics-react-native/blob/829fc80bc8c4f59fa99dadd25083efa422d577f0/packages/core/src/context.ts#L34

2 questions:

- Why do we need to add a condition to get the `deviceId`?
- If the condition is necessary, why `getContextInfo` is not passing the key accordingly?

**Comment by alanjcharles** [comment]
@Kerumen  i believe we made this optional (conditional) because Google has recently changed their consent policy so we can't collect it it automatically anymore. To answer your second question, looks like it might be another bug. Sorry you're running into so many today. I'll add it to the list for this week and keep you posted.

**Comment by Kerumen** [comment]
@alanjcharles No worries! That's the purpose of a beta test. Happy to help, don't hesitate to ping me if you have something to try out.
