### ISSUE TITLE
AnonymousId support

### ISSUE THREAD

**Issue by jchristianhall** [segmentio/analytics-react-native#41]
I'm using `@segment/analytics-react-native - ^0.0.1-beta.3` in order to replicate some functionality in a new React Native app. Based on the documentation, it looks like the iOS SDK has a `getAnonymousId` [method](https://segment.com/docs/libraries/ios#anonymousid), but this project does not. Is it possible to access the `anonymousId` using `analytics-react-native`? I'm trying to prevent multiple `identify` calls if a user has already been identified.

**Comment by f2prateek** [comment]
We're taking a look at at adding an API for this. 

However, could you clarify how this would help your use case however? Wouldn't something like this work as well:

```
let hasCalledIdentify = storage.get("hasCalledIdentify")
if (!hasCalledIdentify) {
  analytics.identify(...)
}
storage.set("hasCalledIdentify", true)
```

How would adding an `analytics.getAnonymousId` method help here?

**Comment by jchristianhall** [comment]
At the time I was trying to implement this, I was trying to mirror the strategy we had used on the web. I think your suggestion may work for our use case though. Unfortunately, the project that I was working on is on hold, so I won't get to try your suggestion until we start back. I'll close this for now, but thanks for getting back to me!

**Comment by DBCintron** [comment]
@f2prateek Wanted to check-in on this as I am in a position where I need access to the anonymousId for a user prior to identify call.

In the current version it looks like the Segment Client's user info should provide the anonymousId, correct? I am a bit confused because when I check the anonymousId here it appears to be different (following the format [here](https://segment.com/docs/connections/spec/identify/#example)) than what we see our destination receiving 🤔 (which follows the UUID format). 

 https://github.com/segmentio/analytics-react-native/blob/master/packages/core/src/analytics.ts#L112
