### ISSUE TITLE
Invariant Violation: new NativeEventEmitter() requires a non-null argument

### ISSUE THREAD

**Issue by wdospinal** [segmentio/analytics-react-native#482]
I get this error on running --> react-native ios

- `analytics-react-native` version: 2.1.9
- Integrations versions (if used): @segment/analytics-react-native-plugin-firebas ^0.2.1
- React Native version: 0.66.4
- iOS or Android or both? -iOS

**Steps to reproduce**
yarn add @segment/analytics-react-native @segment/sovran-react-native @react-native-async-storage/async-storage 
yarn add @segment/analytics-react-native-plugin-firebase

```
The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/wdospinal/Library/Developer/Xcode/DerivedData/dollarideDriverMobile-eunjnfxvxmjjxogcggkhttzbgoct/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-337605CB7CDF90939BEBF863ED22C375.sh (in target 'FBReactNativeSpec' from project 'Pods')
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'segment-analytics-react-native' from project 'Pods')
(2 failures)
```

**Expected behavior**
Run without issues

**Actual behavior**
![Simulator Screen Shot - iPhone 13 - 2022-03-23 at 12 53 15](https://user-images.githubusercontent.com/9275207/159764477-b6651ca0-02bd-49bd-8703-3632c65d0ade.png)

**Comment by altonchaney** [comment]
I'm running into the same issue with a different plugin.

`analytics-react-native` version: 2.1.10
Integrations versions (if used): @segment/analytics-react-native-plugin-adjust ^0.2.1
React Native version: 0.66.4
iOS or Android or both? iOS

When I remove `segmentClient.add({ plugin: new AdjustPlugin() });` from my App.tsx file everything works fine but when it's included I get the exact same error as @wdospinal

**Comment by altonchaney** [comment]
I was able to resolve the issue on my end. Looks like I was referencing a readme version a few days old and this got resolved / cleared up in the latest release. In my case, I just needed to install the `react-native-adjust` package in addition to the plugin package `@segment/analytics-react-native-plugin-adjust`.

For Firebase you'll need to install both `@react-native-firebase/app` and  `@react-native-firebase/analytics` in addition to `@segment/analytics-react-native-plugin-firebase`. Be sure to check the current Firebase plugin [readme](https://github.com/segmentio/analytics-react-native/tree/master/packages/plugins/plugin-firebase) in case anything else was updated since you initially set that up.
