### ISSUE TITLE
[Question] Identify calls more than once with different identifier

### ISSUE THREAD

**Issue by tanoto-the-explorer** [segmentio/analytics-react-native#590]
Hi,

This is a question I have relating to calling `Identify` more than once with different identifier. I have requirements from marketing team about this, but I don't think it is a best practice. supposedly:

```
analytics.identify(user1_id, params1)
analytics.track("event from user 1") // should track the events with user1_id as identifier

analytics.identify(user2_id, params2)
analytics.track("event from user 2") // should track the events with user2_id as identifier
```

Is this possible?

Thanks.

**Comment by oscb** [comment]
This is possible, however we currently have a bug around `identify` calls immediately followed by `track` calls where the user data is not being populated (https://github.com/segmentio/analytics-react-native/issues/584) which might impact this scenario (in particular something like the code you got above). 

It is not a problem if your calls are sent at different times though (or after a timeout). It is just due to concurrency. We're working on a fix regardless.
