### ISSUE TITLE
Amplitude Sessions 5 minute limit

### ISSUE THREAD

**Issue by trevorzablocki2** [segmentio/analytics-react-native#601]
In `@segment/analytics-react-native` V1 Amplitude sessions were not limited by this library but limited by the code implementing it. Now the Amplitude plugin enforces that sessions are no longer than 5 minutes.

- `analytics-react-native` version: 2.3.2
- Integrations versions (if used): @segment/analytics-react-native-plugin-amplitude-session@0.2.1
- React Native version: 0.66.4
- iOS or Android or both? Both

**Steps to reproduce**
- Install @segment/analytics-react-native
- Install @segment/analytics-react-native-plugin-amplitude-session
- create segment client
- segmentClient.add({ plugin: new AmplitudeSessionPlugin() });

**Expected behavior**
I would expect the session to not change until I manually end it or start a new session for Amplitude.

**Actual behavior**
The Amplitude session is restarted every 300 seconds.

**Comment by oscb** [comment]
I believe this is a  bug in the implementation of AmplitudePlugin. There's a limit of 5 minutes between events for being in a single session which I believe was the intention of the current code, however right now the session is not refreshed if there's an event fired during a session (it should extend to 5 minutes again, and so on).
Will fix.

**Comment by Wiingaard** [comment]
For me `sessionId` is always set to `-1`.. [`startSession`](https://github.com/segmentio/analytics-react-native/blob/36c8e15a86e5c7c25041dd2ef552f0bc6ff4abfd/packages/plugins/plugin-amplitudeSession/src/AmplitudeSessionPlugin.tsx#L26) is never called, because `key = 'Actions Amplitude';` of the plugin, doesn't match the `key in integrations` which is just `"Amplitude"`.. I don't know if this is on me, all I did to initialise the Plugin was `segmentClient.add({ plugin: new AmplitudeSessionPlugin() });`, am I missing any steps?

I'm also running:
- analytics-react-native version: 2.3.2
- Integrations versions (if used): @segment/analytics-react-native-plugin-amplitude-session@0.2.1

**Comment by alanjcharles** [comment]
@Wiingaard  do you have the correct Destination added in your Segment workspace? When I add `Amplitude Actions` and log the integration settings, I am getting the correct key. However, If I add `Amplitude` as a Destination, the key is incorrect. We recommend using `Amplitude Actions` as it removes the need for an Amplitude Device Mode SDK.
![image](https://user-images.githubusercontent.com/50601149/179836149-f4d25e5b-3e2e-4095-ae34-d0404b2b33de.png)

**Comment by alanjcharles** [comment]
resolved in [`@segment/analytics-react-native-plugin-amplitude-session 0.3.1`](https://www.npmjs.com/package/@segment/analytics-react-native-plugin-amplitude-session) please let us know if you have any other issues

**Comment by robWood-unmind** [comment]
hey @alanjcharles sorry for surfacing a closed issue here but the issue Wiingaard [highlighted](https://github.com/segmentio/analytics-react-native/issues/601#issuecomment-1188821430) still seems to exist - I'm using an Amplitude Actions destination but the `key` in `integrations` is still `Amplitude` (using `@segment/analytics-react-native-plugin-amplitude-session@0.3.1`) 🤔 

Not sure if I'm missing something else?

![image](https://user-images.githubusercontent.com/77972963/186902554-9105eb70-d6a3-47a7-86c9-6b25ab281206.png)
