### ISSUE TITLE
Use @segment/analytics-react-native-appsflyer

### ISSUE THREAD

**Issue by paolitaclo** [segmentio/analytics-react-native#61]
I am trying to use the AppsFlyer integration in our project. 
I have this 
```
import analytics from '@segment/analytics-react-native';
import AppsFlyer from '@segment/analytics-react-native-appsflyer';
...
...
analytics
    .setup('MY_KEY', {
      using: [AppsFlyer],
      recordScreenViews: true,
      trackAppLifecycleEvents: true,
      trackAttributionData: true,
      ios: {
        trackAdvertising: true,
        trackDeepLinks: true
      },
      android: {
        flushInterval: 60,
        collectDeviceId: true
      }
    })
```
I also added `pod 'RNAnalyticsIntegration-AppsFlyer', :path => '../node_modules/@segment/analytics-react-native-appsflyer'` in the Podfile since it was throwing the error `Failed to load Appsflyer integration native module`

When I go to the segment debugger I am not able to see the integration in the payload. Is there something else I am missing?

**Comment by theonetheycallneo** [comment]
If you are looking for a non-cocoapods solution:

https://github.com/FreebirdRides/segment-analytics-react-native-appsflyer

**Comment by CapitanRedBeard** [comment]
@theonetheycallneo I've install the core analytics SDK via Carthage and it's worked great so far however I also can't get the AppsFlyer integration working (Running into this issue #30 ).

What are the steps to do what you've done in that repo to get AppsFlyer working in my package? Doesn't seem like its a npm package so did you just put all these files into this project directly?

**Comment by GuillaumeLachaud** [comment]
Same here: `integrations` payload in the debugger shows my two others integrations:

`integrations": {
    "Amplitude": false,
    "Firebase": false
  }` (Don't know what the `false` boolean means but at least it works fine. But AppsFlyer is missing.

I noticed that both Segment's [documentation](https://segment.com/docs/destinations/appsflyer/) and AppsFlyer [documentation](https://github.com/AppsFlyerSDK/AppsFlyer-Segment-Integration) state the following:

_After you build and release to the app store, we start translating and sending your data to AppsFlyer automatically._

_After you build and release to the app store, your data is translated and sent to AppsFlyer automatically._

Does that mean we should not expect any data or integration with the debug builds?

**Comment by sheydarezaee** [comment]
I have same problem here, the payload integrations for appsflyer is empty.

**Comment by GuillaumeLachaud** [comment]
Does anyone have information about what this payload means ? I think we are misleaded. It's ok for it to be empty.

According to Segment's [documentation](https://segment.com/docs/sources/mobile/android/), we can see:

_If you are using device-based connection mode, you should see the value of that integration set to false in the `integrations` object. That means that the data is being sent from the device to the destination SDK, and not through Segment’s servers. This is expected if you elected to use a device-based connection mode destination’s SDK with Segment’s during installation._

Not having AppsFlyer in `integrations` is not a deal breaker. I went to the destination's event delivery tab and see that Segment failed to deliver events to AppsFlyer. So it means, the App is sending events to Segment correctly already. Trying to use the Event tester, it fails complaining with the following:

```
Validation Error AppsFlyer Device ID (`integrations.AppsFlyer.appsFlyerId`) is required to send server to server events.
```

It looks like the events payload must contain this very specific appsFlyerId for the integration to work. I'm debugging the SDKs right now to figure out what's happening and will keep you posted.

**Comment by GuillaumeLachaud** [comment]
Ok, something is not working as expected indeed:

Using event tester in Segment, I added the following object

```
  "integrations": {
    "AppsFlyer": {"appsFlyerId":whatever_id}
  },
```

and it sent the event to AppsFlyer correctly.

**Comment by sheydarezaee** [comment]
@GuillaumeLachaud I get exactly the same error when I test events from Segment to be seen in AppsFlyer, and get same error
`Validation Error AppsFlyer Device ID (`integrations.AppsFlyer.appsFlyerId`) is required to send server to server events.`
Meaning somehow we need to pass in `{ AppsFlyer: <appsFlyerId> }` as a part of the events payload when tracking events through Segment

**Comment by sheydarezaee** [comment]
@GuillaumeLachaud where did you add that Object? Don't you need to implement that in your project on each track event?

**Comment by GuillaumeLachaud** [comment]
I just added it in the Event tester on Segment's dashboard to see if this is the missing piece we need. It turns out it is. Now we need to figure out why the SDK isn't sending this as part of the payload which each event. I'm currently playing with AppsFlyer Android [sample app](https://github.com/AppsFlyerSDK/AppsFlyer-Segment-Integration)  to understand what's happening. As the RN SDK directly relies on both native SDKs, I highly doubt the issue is coming from this specific SDK.

**Comment by sheydarezaee** [comment]
@GuillaumeLachaud , That's right, just passed that object to the tester resolved appsflyer error. 
Here is a node.js example of implementing integrations on the payload:

```
// node.js library example
analytics.track({
  event: 'Membership Upgraded',
  userId: '97234974',
  context: {
    device: {
      type: 'ios',
      advertisingId: '159358'
    }
  },
  integrations: {
    AppsFlyer: {
      appsFlyerId: '1415211453000-6513894'
    }
  }
});
```
Need to integrate similar payload for RN.

**Comment by GuillaumeLachaud** [comment]
For a start, when using the sample app, I do get the following:

```
"integrations": {
    "AppsFlyer": false
  },
```

but still no `appsFlyerId`. According to 
>
> _If you are using device-based connection mode, you should see the value of that integration set to false in the `integrations` object. That means that the data is being sent from the device to the destination SDK, and not through Segment’s servers. This is expected if you elected to use a device-based connection mode destination’s SDK with Segment’s during installation._

It means that now, the SDK is sending all its data through the Device based SDK rather than Segment's servers. See https://segment.com/docs/destinations/#connection-modes for Cloud vs Device delivery modes. 

Looking at Android logs of this sample app, everything is going well:

```
2019-07-08 17:38:37.584 13761-14011/com.appsflyer.segment.app.test I/AppsFlyer_4.10.0: AppsFlyerLib.sendTrackingWithEvent
2019-07-08 17:38:37.585 13761-14011/com.appsflyer.segment.app.test I/AppsFlyer_4.10.0: url: https://events.appsflyer.com/api/v4/androidevent?buildnumber=4.10.0&app_id=com.appsflyer.segment.app.test
2019-07-08 17:38:37.585 13761-14011/com.appsflyer.segment.app.test I/AppsFlyer_4.10.0: data: {"device":"generic_x86_64","firstLaunchDate":"2019-07-09_003428+0000","installDate":"2019-07-09_003426+0000","sdk":"25","carrier":"Android","date1":"2019-07-08_173426-0700","cksm_v1":"1bab729387024ef4bfac5fb56836bf60b9","tokenRefreshConfigured":false,"af_preinstalled":"false","advertiserIdEnabled":"true","iaecounter":"21","sc_o":"p","appsflyerKey":"Q********************9","lang_code":"en","ivc":false,"registeredUninstall":false,"app_version_name":"1.0","lang":"English","gaidError":"-1: ClassNotFoundException |","eventName":"TESTdsfds","advertiserId":"b3936b2b-0f50-43d2-9683-65291a650c6f","isGaidWithGps":"false","deviceData":{"dim":{"x_px":"1080","y_px":"1794","size":"2","xdp":"420.0","d_dpi":"420","ydp":"420.0"},"build_display_id":"sdk_google_phone_x86_64-userdebug 7.1.1 NYC 5464897 test-keys","arch":"","cpu_abi":"x86_64","cpu_abi2":""},"appUserId":"a user's id","af_v2":"37d4e3f4df9367e4ff87a337efb8d5a5664a835e","deviceType":"userdebug","af_v":"a15793a4811d529c6ca41ada662596cfd43e217f","app_version_code":"1","eventValue":"{}","af_events_api":"1","network":"WIFI","platformextension":"android_segment","operator":"Android","country":"US","date2":"2019-07-08_173426-0700","brand":"Android","prev_event":"{\"prev_event_timestamp\":\"1562632717410\",\"prev_event_value\":\"{}\",\"prev_event_name\":\"TESTdsfds\"}","af_timestamp":"1562632717556","uid":"1562632468688-1236746790327706930","isFirstCall":"false","kef456e":"a6920720ff1d9641481b0c531b0d591a1c0d5a1f19","counter":"1","model":"Android SDK built for x86_64","product":"sdk_google_phone_x86_64"}
2019-07-08 17:38:37.597 13761-14010/com.appsflyer.segment.app.test I/AppsFlyer_4.10.0: response code: 200
```

Data flow as expected : Segment SDK delegates everything to the AppsFlyer SDK which in turns calls its servers. You can notice that there is **no** `appsFlyerId` specified. This is because `appsFlyerId` is only required for server-to-server interactions. See documentation at [AppsFlyer](https://support.appsflyer.com/hc/en-us/articles/207034486-Server-to-Server-Events-API#Setup), which Segment needs to use when it's tunneling data from its SDK to AppsFlyer.

**Let's take a step back to sum this up**:
When we use the Android Native AppsFlyer-Segment integration SDK, it correctly uses the Device based connection mode, that doesn't need the `appsFlyerId`.

When we use the RN SDK integration, for some reason, this acts as for a web client: it goes through the Segment pipes and thus requires `appsFlyerId` to be specified.

Now we need to figure out why the RN integration behaves differently than the Native integration

**Comment by GuillaumeLachaud** [comment]
I did something interesting: on Segment, I switched my source from being a Native Android app to be a React Native app. I didn't change anything into my sample app except the Segment key. 

And now the payload doesn't have

```
"integrations": {
    "AppsFlyer": false
  }
``` anymore. 

It looks like Segment does something different in terms of SDK configuration depending on the type of Source (Native Android or React Native). This definitely looks like something wrong on their end on the server. I'll try to see if I can open a ticket somewhere for support.

**Comment by GuillaumeLachaud** [comment]
I opened a support ticket and will keep this thread posted.

**Comment by sheydarezaee** [comment]
That's definitely interesting! I am on RN an this is part of my payload: `"integrations": {},`
I got access to the AppsFlyerId through:
```
import appsFlyer from 'react-native-appsflyer'
appsFlyer.getAppsFlyerUID((uidError, appsFlyerUID) => {
      if (uidError) {
        error(uidError)
      } else {
        log(`on getAppsFlyerUID: ${appsFlyerUID}`)
        dispatch(setAppsflyerDeviceId(appsFlyerUID))
      }
    })
```
And trying to implement `integrations` object 
```
  "integrations": {
    "AppsFlyer": {"appsFlyerId":whatever_id}
  },
```
as a part of the payload. 
I am not sure if it's an okay approach.
Since `using: [AppsFlyer]` should fill the `integrations` automatically but it does not

```analytics
    .setup(Config.SEGMENT_API_KEY, {
      using: [AppsFlyer],
      recordScreenViews: true,
      trackAppLifecycleEvents: true,
      trackAttributionData: true,

      android: {
        flushInterval: 60,
        collectDeviceId: true,
      },
      ios: {
        trackAdvertising: true,
        trackDeepLinks: true,
      },
    })
    .then(() => log('Segment analytics is initiated'))
    .catch(err => error('Segment anylytics failed', err))
```

**Comment by GuillaumeLachaud** [comment]
In the meantime, there's a workaround. 

Instead of having one single React-Native Source in Segment, create two sources: one native android, and one native iOS. In your code, initialize the Segment's SDK with the right key depending on the platform. And on Segment's dashboard, have the two sources send to the same AppsFlyer destination.

Note that this might have unintended and unforeseen side effects, is not ideal solution, and should only just be used as a temporary hack.

**Comment by sheydarezaee** [comment]
> I opened a support ticket and will keep this thread posted.

Cool!

**Comment by GuillaumeLachaud** [comment]
@sheydarezaee That's also definitely an approach to consider if there is a way to tweak this piece of the payload. But I don't know if you can do that in a clean way.

**Comment by sokoloff06** [comment]
Hey there! The situation here is the following:

When AppsFlyer SDK wrapper is used, when you make calls to Segment SDK it calls relevant AppsFlyer SDK methods automatically. As a result, there are 2 requests being made from the app: to AppsFlyer and to Segment.

When event is sent to Segment it has this part in the payload:
```
"integrations": {
    "AppsFlyer": false
  }
```
which is correct. It means that events were sent to AppsFlyer from the app itself.

In the event sent to Segment there is no AppsFlyer ID and in fact Segment doesn't really forward events to AppsFlyer because they have already been sent directly from AppsFlyer SDK.

If you are trying to validate the payload you get in Segment (in debugger let's say) through the Event Tester you shouldn't do that because in reality it tests something that is not actually happening.

I hope that helps!

**Comment by aharon87** [comment]
does anyone have a solution?

**Comment by ivansnek** [comment]
@GuillaumeLachaud did you got this resolved? I'm facing the same issue.
Do I need to implement any native side integration if I'm using, `AppsFlyer` within `using` property:
```
import analytics from '@segment/analytics-react-native';
import AppsFlyer from '@segment/analytics-react-native-appsflyer';

analytics
    .setup(Config.SEGMENT_API_KEY, {
      using: [AppsFlyer],
...
```
Current package versions:
   ```
"@segment/analytics-react-native": "^1.3.2",
"@segment/analytics-react-native-appsflyer": "^1.3.2",
```

**Comment by Lucasdsk** [comment]
Hey @GuillaumeLachaud did you have an answer for your ticket? I'm facing the same issue.
Also @ivansnek, @sheydarezaee  did you get a solution as well?

Are you folks using this workaround?
https://github.com/segmentio/analytics-react-native/issues/61#issuecomment-509446953

Package versions:
```
"@segment/analytics-react-native": "^1.3.2",
"@segment/analytics-react-native-appsflyer": "^1.3.2",
```

There's my code.

```
await analytics
    .setup(SEGMENT_WRITE_API_KEY, {
      using: [AppsFlyer],
      // Record certain application events automatically!
      trackAppLifecycleEvents: true,
      // Record screen views automatically!
      recordScreenViews: true,
      android: {
        flushInterval: 60000,
        collectDeviceId: true,
      },
      ios: {
        trackAdvertising: true,
        trackDeepLinks: true,
      },
    })
    .then(() => {
      Sentry.addBreadcrumb({
        category: 'Configure Analytics',
        message: 'Analytics configured',
        level: Sentry.Severity.Info,
      });
    })
    .catch((analyticsSetupError) => {
      Sentry.captureException(analyticsSetupError);
    });
```

**Comment by nando0208** [comment]
@bsneed Sorry, Is it closed because it is solved?

I'm having the same issue in my side just for iOS devices.
Debugging I found some intermittent behaviour in this part of the [code](https://github.com/segmentio/analytics-react-native/blob/40683c7c70d4a750d947fe7117962b0c09cb1936/packages/core/ios/RNAnalytics/RNAnalytics.m#L105)

This code is using the [RNAnalyticsIntegrations](https://github.com/segmentio/analytics-react-native/blob/40683c7c70d4a750d947fe7117962b0c09cb1936/packages/core/ios/RNAnalytics/RNAnalytics.m#L18) to add on integration factories to `SEGAnalyticsConfiguration`. 

This is a `static NSMutableSet` and it is updated when this integrations are setup.
https://github.com/segmentio/analytics-react-native/blob/40683c7c70d4a750d947fe7117962b0c09cb1936/packages/core/ios/RNAnalytics/RNAnalytics.m#L18

**Setup Method Examples**
[AppsFlyer](https://github.com/segmentio/analytics-react-native/blob/f0febdbf229533137c64091e460f530448339cec/packages/integrations/patches/%40segment/analytics-react-native-appsflyer/ios/main.m#L27)
[Facebook](https://github.com/segmentio/analytics-react-native/blob/6ec053b1e2c5fcb1e7276c64ade9752c0417a615/packages/integrations/patches/%40segment/analytics-react-native-facebook-app-events-ios/ios/main.m#L27)

However, sometimes the method [RNAnalytics.setup](https://github.com/segmentio/analytics-react-native/blob/40683c7c70d4a750d947fe7117962b0c09cb1936/packages/core/ios/RNAnalytics/RNAnalytics.m#L105) is called before RNAnalyticsIntegrations being updated.

Is this behaviour expected?
Can we do something to prevent this to happen?

**Comment by nando0208** [comment]
@bsneed Here is some logs I added to prove this behaviour.

```
2021-03-30 18:23:30.648295-0300 nomad_mobile_app[27521:152492] AF_TEST addIntegration: SEGFirebaseIntegrationFactory
2021-03-30 18:23:30.648317-0300 nomad_mobile_app[27521:152488] AF_TEST addIntegration: BNCBranchIntegrationFactory
2021-03-30 18:23:30.648639-0300 nomad_mobile_app[27521:152503] AF_TEST start USE {(
    <SEGFirebaseIntegrationFactory: 0x600003b9c460>,
    <BNCBranchIntegrationFactory: 0x600003b84830>
)}
2021-03-30 18:23:30.648843-0300 nomad_mobile_app[27521:152461] AF_TEST addIntegration: SEGAppsFlyerIntegrationFactory
```

I added this two logs:

RNAnalytics.m, ln 24
```
+(void)addIntegration:(id)factory {
    NSLog(@"AF_TEST addIntegration: %@", [factory class]);
    [RNAnalyticsIntegrationsLock lock];
    [RNAnalyticsIntegrations addObject:factory];
    [RNAnalyticsIntegrationsLock unlock];
} 
```
RNAnalytics.m, ln 105
```
    NSLog(@"AF_TEST start USE %@", RNAnalyticsIntegrations);
    for(id factory in RNAnalyticsIntegrations) {
        [config use:factory];
    }
```
I suspect this error is related with this part, because this will happen if this code don't wait all integrations be called.
https://github.com/segmentio/analytics-react-native/blob/e522f6ef0eddd30c7a2952fe9dc9ee860bda81cb/packages/core/src/configuration.ts#L36

**Comment by alejogo4** [comment]
> Hola @GuillaumeLachaud, ¿tenías una respuesta para tu boleto? Estoy enfrentando el mismo problema.
> También @ivansnek , @sheydarezaee , ¿ obtuviste una solución también?
> 
> ¿Ustedes están usando esta solución alternativa?
> [# 61 (comentario)](https://github.com/segmentio/analytics-react-native/issues/61#issuecomment-509446953)
> 
> Versiones del paquete:
> 
> ```
> "@segment/analytics-react-native": "^1.3.2",
> "@segment/analytics-react-native-appsflyer": "^1.3.2",
> ```
> 
> Ahí está mi código.
> 
> ```
> await analytics
>     .setup(SEGMENT_WRITE_API_KEY, {
>       using: [AppsFlyer],
>       // Record certain application events automatically!
>       trackAppLifecycleEvents: true,
>       // Record screen views automatically!
>       recordScreenViews: true,
>       android: {
>         flushInterval: 60000,
>         collectDeviceId: true,
>       },
>       ios: {
>         trackAdvertising: true,
>         trackDeepLinks: true,
>       },
>     })
>     .then(() => {
>       Sentry.addBreadcrumb({
>         category: 'Configure Analytics',
>         message: 'Analytics configured',
>         level: Sentry.Severity.Info,
>       });
>     })
>     .catch((analyticsSetupError) => {
>       Sentry.captureException(analyticsSetupError);
>     });
> ```

Were you able to solve this problem? I am having the same problem for android, in Segment, in the place of the integrations the AppsFlyer value AppsFlyer: false, however I am sending in the track events
```
const optionsAppsFlyer = {
   integrations: {
     AppsFlyer: true
   },
};

track(event: string, properties?: JsonMap, options?: Options) {
    
    let _options = { ...(options || {}), ...optionsAppsFlyer };

    analytics.track(event, properties, _options);
},
```

**Comment by GabrielLim-FastCo** [comment]
Is there any guide on how to define separate `Dev Key` for separate Platform on v2's library?
