### ISSUE TITLE
IDFA fallback value

### ISSUE THREAD

**Issue by reichhartd** [segmentio/analytics-react-native#621]
**Actual behavior**

We use the AppsFlyer plugin in combination with the IDFA plugin. We also send the AppsFlyer ID and the IDFA to our backend, as events are also sent from there to AppsFlyer via Segment.

If the user has Tracking Enabled, and the IDFA is available, everything works fine.

However, if Tracking has been denied, we send `undefined` to our backend, the IDFA plugin sends an alternate value to Segment. This prevents the data from being matched at AppsFlyer.

**Expected behavior**

So we would like to customize the IDFA plugin, and also send an empty value to Segment for this case, as this is the correct behavior from our point of view.

-   `analytics-react-native` version:

    `"@segment/analytics-react-native": "^2.5.0",`

-   Integrations versions (if used):

    `"@segment/analytics-react-native-plugin-appsflyer": "^0.4.0",`
    `"@segment/analytics-react-native-plugin-idfa": "^0.4.0",`
    `"@segment/sovran-react-native": "^0.4.3",`

-   React Native version:

    `"react-native": "0.68.2",`

-   iOS or Android or both?

-   [x] iOS
-   [ ] Android

**Comment by alanjcharles** [comment]
Hi @reichhartd thanks for reaching out. We send the `IDFV` value if the `IDFA` value is `undefined`. This is also how our other iOS libraries work (see [Analytics Swift](https://github.com/segmentio/analytics-swift/blob/main/Examples/other_plugins/IDFACollection.swift#L88)). To maintain parity across our products, this is not something we will make a fix for. However, if you'd like you can create and implement your own `idfa-plugin` that sets the value to `undefined` rather than `idfv`. 

You can essentially copy the logic in the current `idfa-plugin` and simply change the [fallback value found here](https://github.com/segmentio/analytics-react-native/blob/master/packages/plugins/plugin-idfa/ios/AnalyticsReactNativePluginIdfa.swift#L56). You can also [reference this documentation](https://github.com/segmentio/analytics-react-native#writing-your-own-plugins) when building your own plugins. Hope this helps!

**Comment by reichhartd** [comment]
Hi @alanjcharles 
thanks a lot for your answer! We have since created our own plugin, and are using it.

However, I would be happy if there would be a configuration option in the main repository. Similar to [`shouldAskPermission`](https://github.com/segmentio/analytics-react-native/blob/master/packages/plugins/plugin-idfa/src/IdfaPlugin.tsx#L18), I would add a parameter `useIDFVAsFallbackValue`, and accordingly then take this as the fallback value, or leave it `undefined`. This way it would not be a breaking change.

If that is ok, I would create a pull request.
