### ISSUE TITLE
The Swift pod `segment-analytics-react-native` depends upon `React-Core`, which does not define modules.

### ISSUE THREAD

**Issue by nfasate** [segmentio/analytics-react-native#683]
The Swift pod `segment-analytics-react-native` depends upon `React-Core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

I tried to set :modular_headers => true for specifically this pod in Podfile still getting same error.
`pod 'segment-analytics-react-native', :modular_headers => true, :path => '../node_modules/@segment/analytics-react-native'`

- `analytics-react-native` version: - 2.0.0-pilot
- React Native version: - 0.62.0
- iOS or Android or both?  - on iOS only

**Comment by oscb** [comment]
The dependency on `React-Core` is by design, as this is the recommended solution for another set of build issues on newer versions of Xcode.

I do notice that you are using `2.0.0-pilot` I would recommend using the latest versions. It might also be due to the version of RN.

I do think you will have to set `use_modular_headers!` globally for the package to work, but this seems to be more of a React-Native issue. I don't think ` :modular_headers => true,` works if only applied to a particular module due to how autolinking works in RN, specially cause the issue comes from a dependency of our library.
