### ISSUE TITLE
destination plugins never run if the plugin settings are undefined

### ISSUE THREAD

**Issue by nicolas-godefroy-dev** [segmentio/analytics-react-native#717]
- `analytics-react-native` version: ^2.9.0
- Integrations versions (if used): @segment/analytics-react-native-plugin-firebase
- React Native version: 0.69.6
- iOS or Android or both?  both

**Steps to reproduce**
If the plugins are added like this no events seem to be sent
`client.add({ plugin: new FirebasePlugin()  })`

But if we define an empty object as settings the plugin seems to work, maybe we should update the documentation 
or change this behavior
`client.add({ plugin: new FirebasePlugin(), settings: {} })`

**Comment by alanjcharles** [comment]
Hi @nicolas-godefroy-dev. This is likely happening because you don't have Firebase enabled in your Segment workspace. I can recreate your issue in this way. This is because all destination plugins check for settings with this [`isEnabled()`](https://github.com/segmentio/analytics-react-native/blob/master/packages/core/src/plugin.ts#L122) method they inherit. If settings from the Segment workspace aren't present, the destination is disabled and this error happens. Please make sure you have a Firebase destination connected to your React Native source and that it is enabled. If you are still running into issues please feel free to reach out to friends@segment.com. They'll be able to offer guidance/escalate bugs in a much more efficient way. Thanks!
