### ISSUE TITLE
Integration of Segment on React Native 0.60.4

### ISSUE THREAD

**Issue by JHSoriano** [segmentio/analytics-react-native#722]
having trouble on installing this segment on react native and while building this is showing
<img width="404" alt="Screen Shot 2022-11-28 at 11 29 29 AM" src="https://user-images.githubusercontent.com/84517661/204186836-b64b7734-ea20-466c-b158-c4b2141dbfdc.png">

- `analytics-react-native` version: "^2.9.1"
- Integrations versions (if used):
- React Native version: 0.60.4
- iOS or Android or both? IOS, not yet tried on android

**Steps to reproduce**
<img width="1465" alt="Screen Shot 2022-11-28 at 11 31 20 AM" src="https://user-images.githubusercontent.com/84517661/204187443-be0b10b0-b06a-46e0-bc13-24941b784bf3.png">

**Expected behavior**
should successfully build
**Actual behavior**
<img width="404" alt="Screen Shot 2022-11-28 at 11 29 29 AM" src="https://user-images.githubusercontent.com/84517661/204186836-b64b7734-ea20-466c-b158-c4b2141dbfdc.png">

**Comment by alanjcharles** [comment]
Hi @JHSoriano please update your version of React Native. The oldest we fully support is `0.67.2` but typically, anyone on `0.65.0` and up seem to be okay. This is because while we don't rely on react native a lot in this sdk, we do rely on hooks and native modules, both of which have had fundamental changes in recent versions of react native. I hope this helps, If you're still running into issues, please reach out to `friends@segment.com` for additional troubleshooting support. Thanks!
