### ISSUE TITLE
Track session events in Amplitude

### ISSUE THREAD

**Issue by trevorzablocki2** [segmentio/analytics-react-native#726]
## Summary
In V1 of this library, Amplitude would receive "Start Session" and "End Session" events through the use of the Amplitude iOS library and the `trackingSessionEvents` field. With V2, these events are no longer sent to Amplitude, so they are no longer trackable in Amplitude.

## Proposed Solution
Is this something this library wants to support for consistency or should we manually call these start/end session events using [Amplitude's RN library](https://github.com/amplitude/Amplitude-TypeScript/tree/main/packages/analytics-react-native)?

**Comment by alanjcharles** [comment]
Hi @trevorzablocki2 this is likely because the classic integration was a device mode integration that relied on the underlying native Amplitude SDKs. The Amplitude Plugin offered in the new library is technically a Destination Action. [You can read more about that here](https://segment.com/docs/connections/destinations/catalog/actions-amplitude/#available-actions-1) but from a high level, it no longer relies on the Amplitude SDK and instead makes it possible to map events to Amplitude in your Segment workspace. I am not certain if this option is available in those mappings, but I would recommend reaching out to `friends@segment.com` for additional troubleshooting support and general guidance. Thanks for reaching out and best of luck!
