### ISSUE TITLE
Destination filter per event tracking support

### ISSUE THREAD

**Issue by rafael-fecha** [segmentio/analytics-react-native#760]
I'm using this package @segment/analytics-react-native and when we call segment.track we would like to filter what are the integrations/destinations for each kind of event that we are sending.
I can see in the method definition only accepts **event name and properties**: https://github.com/segmentio/analytics-react-native/blob/28bbb9eaa6bb012fd0ebfec065fd901e7301a46c/packages/core/src/types.ts#L153

I can see also that there is this plugin: @segment/analytics-react-native-plugin-destination-filters , in the docs just shows how to add it, and then when using the track method how it should be in case we want to define to track an event just for example a Slack, Vero or any other destination ? 

I can see also from version 2.9.0 there was pr merged regarding destination filter support: https://github.com/segmentio/analytics-react-native/pull/685/files#diff-31e1ca337373ece1a71f9ba34799c69ad9db4f0c2f0e2e5c8fa8653984b09a1e, but the readme describes how to add the plugin but not how to use these destinations filter per event track.

I would expect support of passing a integrations parameter to filter where do i want to send this event. This package for nodeJS analytics-node, for example provides this:
  ```track(message: Identity & {
      event: string;
      properties?: any;
      timestamp?: Date | undefined;
      context?: any;
      integrations?: Integrations | undefined;
    }
```

Thank you !

**Comment by oscb** [comment]
Hi Rafael, this is definitely something we should document and provider a better example of how to do it in code.

Question: Do you want to handle this through Segment Cloud or through code in the app? 

The `@segment/analytics-react-native-plugin-destination-filters` is meant to work with the cloud's [Destination Filters](https://segment.com/docs/connections/destinations/destination-filters/) which are configurable through your Segment workspace. It's recommended because these are configurable for both device and cloud mode destinations. When you got these setup you can just add the RN plugin and everything else about filtering is handled automatically based on your cloud rules.

That said, it is also possible to do it in code in the RN library. It has to be done inside a [custom plugin](https://github.com/segmentio/analytics-react-native/tree/master#writing-your-own-plugins), plugins can access and modify the `integrations` part of the object, same as the NodeJS package.

Feel free to [contact Segment support](https://segment.com/help/contact/) either way you choose to go, they will be able to show you more examples of how to set it up!
