### ISSUE TITLE
How to pass UTM info for react native app

### ISSUE THREAD

**Issue by yawei-workmate** [segmentio/analytics-react-native#774]
## Summary
Hi Team, is there any way to pass UTM info like utm_content, utm_campaign through this package to segment?

**Comment by alanjcharles** [comment]
Hi @yawei-workmate thanks for reaching out! We don't have a defined way to handle UTM information in this library. This is because typically customers will use deep links for apps rather than UTM params. We do have a way to handle deep links, which can be found [here](https://github.com/segmentio/analytics-react-native#ios-deep-link-tracking-setup). You could potentially do something similar with sovran and a custom native implementation. Happy to discuss any ideas/concerns you have. You can also reach out to friends@segment.com for a more consistent troubleshooting experience. Thanks again!
