### ISSUE TITLE
Violation of User Data policy

### ISSUE THREAD

**Issue by v-boichuk** [segmentio/analytics-react-native#881]
Application with @segment/analytics-react-native can't pass the Play Console review. 
I've seen other closed issues, but they do not resolve the issue. We migrated to  v2 of segment analytics, also manually set `collectDeviceId` param to false during initialization. Nothing helps.

here is reply from reviewers:

> We reviewed SDKs used by your app and found noncompliant version(s) of SDK(s) which collects persistent device identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers.
> 
> Issue details
> 
> We found an issue in the following area(s):
> 
> SDK: Segment com.segment.analytics.android:analytics (consider upgrading to version 4.10.1)

used version:
- @segment/analytics-react-native": "^2.16.0",
 - @segment/sovran-react-native": "^0.4.3",
- React Native version: 0.65.0
- Android

**Steps to reproduce**
1.Install latest version of Segment analytics libraries. 
2. Submit app to Play console review

**Comment by oscb** [comment]
RN v2 doesn't use the native SDK package `com.segment.analytics.android:analytics` anymore which is the component that is being marked here.

In previous issues this has been due to caches keeping the v1 native modules around.

I suggest making a clean build:
- Clean NPM Modules
- Clean gradle cache: `./gradlew cleanBuildCache`
- Clean any build or intermediates
- Make sure there's no reference to `com.segment.analytics.android` in your Android gradle files (it's not required anymore)

I'm not particularly sure why Android in particular keeps around this module (sometimes) when migrating from v1 but you don't need it.
