### ISSUE TITLE
passing integration object in track method

### ISSUE THREAD

**Issue by mohit23x** [segmentio/analytics-react-native#913]
- `analytics-react-native` version: v2.16.0
- Integrations versions (if used):
- React Native version: v0.72.7
- iOS or Android - both

**Steps to reproduce**
- Call track with (eventName, properties, integration)
- The integration is not sent in the final call and the `integration` data is also not visible in segment dashboard.
- Earlier in v1 the track event was taking the 3rd param, but in v2 the track method is only taking 2 params.
- How to send appsflyerID as part of integrations?

v2 link - https://github.com/segmentio/analytics-react-native/blob/87f34e3ae318f85666ef1b8b94b5646e138bda17/packages/core/src/analytics.ts#L545

v1 link - https://github.com/segmentio/analytics-react-native/blob/cf11d270e163ecc9661a15f0851215160af67796/packages/core/src/analytics.ts#L271

| track v2 (new) | track v1 (old) |
|--------|--------|
| <img width="501" alt="image" src="https://github.com/segmentio/analytics-react-native/assets/36567063/c01fab6b-7cc2-49b8-93f8-adc608ed3170"> | <img width="666" alt="image" src="https://github.com/segmentio/analytics-react-native/assets/36567063/631776c0-075b-4bb1-acdf-24c04e67b080"> |

**Comment by oscb** [comment]
@mohit23x we don't support `integrations` as an argument on v2. That's by design. By default AppsFlyer should be getting all the settings it needs from Segment settings:

https://github.com/segmentio/analytics-react-native/blob/3862b4ec6b3cf26c490fda79f322e05ee6fc7cb1/packages/plugins/plugin-appsflyer/src/types.ts#L1-L9

You can also pass the same settings object when adding the plugin:

```
segmentClient.add({plugin: new AppsflyerPlugin(), settings: {
  // Here
}});
```

I do recommend doing it all through Segment to have more flexibility as those get updated through the cloud.
